package codegen

// Register at package-level var init time (runs before any init() functions).
var _ = registerRaylib()

func registerRaylib() bool {
	RegisterVendorCodegen(&VendorCodegen{
		ModuleFuncs: map[string]map[string]string{
			"rl": {
				// Window management
				"init_window":          "InitWindow",
				"close_window":         "CloseWindow",
				"window_should_close":  "WindowShouldClose",
				"set_target_fps":       "SetTargetFPS",
				"get_screen_width":     "GetScreenWidth",
				"get_screen_height":    "GetScreenHeight",
				"get_screen_size":      "kl_get_screen_size",
				"toggle_fullscreen":    "ToggleFullscreen",
				"is_window_resized":    "IsWindowResized",
				"set_window_title":     "SetWindowTitle",
				"set_window_size":      "SetWindowSize",
				"get_frame_time":       "GetFrameTime",
				"get_time":             "GetTime",
				"get_fps":              "GetFPS",
				// Drawing
				"begin_drawing":        "BeginDrawing",
				"end_drawing":          "EndDrawing",
				"clear_background":     "ClearBackground",
				"begin_mode_2d":        "BeginMode2D",
				"end_mode_2d":          "EndMode2D",
				"begin_mode_3d":        "BeginMode3D",
				"end_mode_3d":          "EndMode3D",
				// Shapes
				"draw_line":            "DrawLine",
				"draw_line_v":          "kl_draw_line_v",
				"draw_circle":          "DrawCircle",
				"draw_circle_v":        "kl_draw_circle_v",
				"draw_rectangle":       "DrawRectangle",
				"draw_rectangle_v":     "kl_draw_rectangle_v",
				"draw_rectangle_rec":   "DrawRectangleRec",
				"draw_rectangle_lines": "DrawRectangleLines",
				"draw_triangle":        "DrawTriangle",
				// Text
				"draw_text":            "DrawText",
				"draw_text_ex":         "DrawTextEx",
				"measure_text":         "MeasureText",
				"load_font":            "LoadFont",
				"unload_font":          "UnloadFont",
				// Textures
				"load_texture":         "LoadTexture",
				"unload_texture":       "UnloadTexture",
				"draw_texture":         "DrawTexture",
				"draw_texture_v":       "kl_draw_texture_v",
				"draw_texture_ex":      "DrawTextureEx",
				"draw_texture_rec":     "DrawTextureRec",
				"draw_texture_pro":     "kl_draw_texture_pro",
				// Input - keyboard
				"is_key_pressed":       "IsKeyPressed",
				"is_key_down":          "IsKeyDown",
				"is_key_released":      "IsKeyReleased",
				"is_key_up":            "IsKeyUp",
				// Input - mouse
				"is_mouse_button_pressed":  "IsMouseButtonPressed",
				"is_mouse_button_down":     "IsMouseButtonDown",
				"is_mouse_button_released": "IsMouseButtonReleased",
				"get_mouse_position":       "kl_get_mouse_position",
				"get_mouse_x":             "GetMouseX",
				"get_mouse_y":             "GetMouseY",
				"get_mouse_wheel_move":    "GetMouseWheelMove",
				// Input - gamepad
				"is_gamepad_available":      "IsGamepadAvailable",
				"is_gamepad_button_pressed": "IsGamepadButtonPressed",
				"is_gamepad_button_down":    "IsGamepadButtonDown",
				"get_gamepad_axis_movement": "GetGamepadAxisMovement",
				// Audio
				"init_audio_device":    "InitAudioDevice",
				"close_audio_device":   "CloseAudioDevice",
				"load_sound":           "LoadSound",
				"unload_sound":         "UnloadSound",
				"play_sound":           "PlaySound",
				"stop_sound":           "StopSound",
				"load_music_stream":    "LoadMusicStream",
				"unload_music_stream":  "UnloadMusicStream",
				"play_music_stream":    "PlayMusicStream",
				"stop_music_stream":    "StopMusicStream",
				"update_music_stream":  "UpdateMusicStream",
				"set_master_volume":    "SetMasterVolume",
				// Misc
				"draw_fps":            "DrawFPS",
				"set_exit_key":        "SetExitKey",
				// Helpers
				"color":     "kl_color",
				"color_rgb": "kl_color_rgb",
				"rect":      "kl_rect",
				"camera2d":  "kl_camera2d",
				"camera3d":  "kl_camera3d",
			},
		},
		ConstNamespaces: map[string]map[string]string{
			"Colors": {
				"LightGray":  "LIGHTGRAY",
				"Gray":       "GRAY",
				"DarkGray":   "DARKGRAY",
				"Yellow":     "YELLOW",
				"Gold":       "GOLD",
				"Orange":     "ORANGE",
				"Pink":       "PINK",
				"Red":        "RED",
				"Maroon":     "MAROON",
				"Green":      "GREEN",
				"Lime":       "LIME",
				"DarkGreen":  "DARKGREEN",
				"SkyBlue":    "SKYBLUE",
				"Blue":       "BLUE",
				"DarkBlue":   "DARKBLUE",
				"Purple":     "PURPLE",
				"Violet":     "VIOLET",
				"DarkPurple": "DARKPURPLE",
				"Beige":      "BEIGE",
				"Brown":      "BROWN",
				"DarkBrown":  "DARKBROWN",
				"White":      "WHITE",
				"Black":      "BLACK",
				"Blank":      "BLANK",
				"Magenta":    "MAGENTA",
				"RayWhite":   "RAYWHITE",
			},
			"Key": {
				"Space":        "KEY_SPACE",
				"Escape":       "KEY_ESCAPE",
				"Enter":        "KEY_ENTER",
				"Tab":          "KEY_TAB",
				"Backspace":    "KEY_BACKSPACE",
				"Delete":       "KEY_DELETE",
				"Right":        "KEY_RIGHT",
				"Left":         "KEY_LEFT",
				"Down":         "KEY_DOWN",
				"Up":           "KEY_UP",
				"LeftShift":    "KEY_LEFT_SHIFT",
				"LeftCtrl":     "KEY_LEFT_CONTROL",
				"LeftAlt":      "KEY_LEFT_ALT",
				"RightShift":   "KEY_RIGHT_SHIFT",
				"RightCtrl":    "KEY_RIGHT_CONTROL",
				"RightAlt":     "KEY_RIGHT_ALT",
				"A": "KEY_A", "B": "KEY_B", "C": "KEY_C", "D": "KEY_D",
				"E": "KEY_E", "F": "KEY_F", "G": "KEY_G", "H": "KEY_H",
				"I": "KEY_I", "J": "KEY_J", "K": "KEY_K", "L": "KEY_L",
				"M": "KEY_M", "N": "KEY_N", "O": "KEY_O", "P": "KEY_P",
				"Q": "KEY_Q", "R": "KEY_R", "S": "KEY_S", "T": "KEY_T",
				"U": "KEY_U", "V": "KEY_V", "W": "KEY_W", "X": "KEY_X",
				"Y": "KEY_Y", "Z": "KEY_Z",
				"F1": "KEY_F1", "F2": "KEY_F2", "F3": "KEY_F3", "F4": "KEY_F4",
				"F5": "KEY_F5", "F6": "KEY_F6", "F7": "KEY_F7", "F8": "KEY_F8",
				"F9": "KEY_F9", "F10": "KEY_F10", "F11": "KEY_F11", "F12": "KEY_F12",
				"Zero": "KEY_ZERO", "One": "KEY_ONE", "Two": "KEY_TWO",
				"Three": "KEY_THREE", "Four": "KEY_FOUR", "Five": "KEY_FIVE",
				"Six": "KEY_SIX", "Seven": "KEY_SEVEN", "Eight": "KEY_EIGHT", "Nine": "KEY_NINE",
			},
			"Mouse": {
				"Left":   "MOUSE_BUTTON_LEFT",
				"Right":  "MOUSE_BUTTON_RIGHT",
				"Middle": "MOUSE_BUTTON_MIDDLE",
			},
			"Gamepad": {
				"LeftStickX":   "GAMEPAD_AXIS_LEFT_X",
				"LeftStickY":   "GAMEPAD_AXIS_LEFT_Y",
				"RightStickX":  "GAMEPAD_AXIS_RIGHT_X",
				"RightStickY":  "GAMEPAD_AXIS_RIGHT_Y",
				"LeftTrigger":  "GAMEPAD_AXIS_LEFT_TRIGGER",
				"RightTrigger": "GAMEPAD_AXIS_RIGHT_TRIGGER",
			},
		},
		ValueTypes: []string{
			"Color", "Rectangle", "Camera2D", "Camera3D",
			"Texture2D", "Font", "Sound", "Music",
		},
		TypeMap: map[string]string{
			"Color":     "Color",
			"Rectangle": "Rectangle",
			"Texture2D": "Texture2D",
			"Texture":   "Texture2D",
			"Font":      "Font",
			"Sound":     "Sound",
			"Music":     "Music",
			"Camera2D":  "Camera2D",
			"Camera3D":  "Camera3D",
		},
		ConstructorTypes: []string{"Color", "Rectangle"},
		ReturnTypes: map[string]string{
			// bool returns
			"window_should_close":      "bool",
			"is_window_resized":        "bool",
			"is_key_pressed":           "bool",
			"is_key_down":              "bool",
			"is_key_released":          "bool",
			"is_key_up":                "bool",
			"is_mouse_button_pressed":  "bool",
			"is_mouse_button_down":     "bool",
			"is_mouse_button_released": "bool",
			"is_gamepad_available":     "bool",
			"is_gamepad_button_pressed":"bool",
			"is_gamepad_button_down":   "bool",
			// int returns
			"get_screen_width":  "int",
			"get_screen_height": "int",
			"get_fps":           "int",
			"measure_text":      "int",
			"get_mouse_x":       "int",
			"get_mouse_y":       "int",
			// float returns
			"get_frame_time":          "float",
			"get_time":                "float",
			"get_mouse_wheel_move":    "float",
			"get_gamepad_axis_movement":"float",
			// vec2 returns
			"get_mouse_position": "vec2",
			"get_screen_size":    "vec2",
			// Texture2D returns
			"load_texture": "Texture2D",
			// Font returns
			"load_font": "Font",
			// Sound returns
			"load_sound": "Sound",
			// Music returns
			"load_music_stream": "Music",
			// Color returns
			"color":     "Color",
			"color_rgb": "Color",
			// Rectangle returns
			"rect": "Rectangle",
			// Camera returns
			"camera2d": "Camera2D",
			"camera3d": "Camera3D",
		},
		DetectIdents: []string{"rl", "Colors", "Key", "Mouse", "Gamepad"},
		DetectModule: "rl",
	})
	return true
}
