// Code generated by tools/gen-raylib/gen.py. DO NOT EDIT.
//
// To regenerate, run:
//   python3 tools/gen-raylib/gen.py path/to/raylib_api.json

#ifndef KL_RAYLIB_H
#define KL_RAYLIB_H

#include "raylib.h"

// --- Manual helpers ---

static inline Color kl_color(int r, int g, int b, int a) {
    return (Color){ (unsigned char)r, (unsigned char)g, (unsigned char)b, (unsigned char)a };
}

static inline Color kl_color_rgb(int r, int g, int b) {
    return (Color){ (unsigned char)r, (unsigned char)g, (unsigned char)b, 255 };
}

static inline Camera2D kl_camera2d(vec2 offset, vec2 target, float rotation, float zoom) {
    Camera2D cam = {0};
    cam.offset = (Vector2){ offset.x, offset.y };
    cam.target = (Vector2){ target.x, target.y };
    cam.rotation = rotation;
    cam.zoom = zoom;
    return cam;
}

static inline Camera3D kl_camera3d(vec3 position, vec3 target, vec3 up, float fovy, int projection) {
    Camera3D cam = {0};
    cam.position = (Vector3){ position.x, position.y, position.z };
    cam.target = (Vector3){ target.x, target.y, target.z };
    cam.up = (Vector3){ up.x, up.y, up.z };
    cam.fovy = fovy;
    cam.projection = projection;
    return cam;
}

static inline Rectangle kl_rect(float x, float y, float w, float h) {
    return (Rectangle){ x, y, w, h };
}

static inline vec2 kl_get_screen_size(void) {
    return (vec2){ (float)GetScreenWidth(), (float)GetScreenHeight() };
}

// --- Auto-generated wrappers (vec2/vec3 conversions) ---

static inline vec2 kl_get_monitor_position(int monitor) { Vector2 _r = GetMonitorPosition(monitor); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_window_position(void) { Vector2 _r = GetWindowPosition(); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_window_scale_dpi(void) { Vector2 _r = GetWindowScaleDPI(); return (vec2){ _r.x, _r.y }; }

static inline Ray kl_get_screen_to_world_ray(vec2 position, Camera camera) { return GetScreenToWorldRay((Vector2){position.x, position.y}, camera); }

static inline Ray kl_get_screen_to_world_ray_ex(vec2 position, Camera camera, int width, int height) { return GetScreenToWorldRayEx((Vector2){position.x, position.y}, camera, width, height); }

static inline vec2 kl_get_world_to_screen(vec3 position, Camera camera) { Vector2 _r = GetWorldToScreen((Vector3){position.x, position.y, position.z}, camera); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_world_to_screen_ex(vec3 position, Camera camera, int width, int height) { Vector2 _r = GetWorldToScreenEx((Vector3){position.x, position.y, position.z}, camera, width, height); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_world_to_screen_2d(vec2 position, Camera2D camera) { Vector2 _r = GetWorldToScreen2D((Vector2){position.x, position.y}, camera); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_screen_to_world_2d(vec2 position, Camera2D camera) { Vector2 _r = GetScreenToWorld2D((Vector2){position.x, position.y}, camera); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_mouse_position(void) { Vector2 _r = GetMousePosition(); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_mouse_delta(void) { Vector2 _r = GetMouseDelta(); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_mouse_wheel_move_v(void) { Vector2 _r = GetMouseWheelMoveV(); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_touch_position(int index) { Vector2 _r = GetTouchPosition(index); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_gesture_drag_vector(void) { Vector2 _r = GetGestureDragVector(); return (vec2){ _r.x, _r.y }; }

static inline vec2 kl_get_gesture_pinch_vector(void) { Vector2 _r = GetGesturePinchVector(); return (vec2){ _r.x, _r.y }; }

static inline void kl_draw_pixel_v(vec2 position, Color color) { DrawPixelV((Vector2){position.x, position.y}, color); }

static inline void kl_draw_line_v(vec2 startPos, vec2 endPos, Color color) { DrawLineV((Vector2){startPos.x, startPos.y}, (Vector2){endPos.x, endPos.y}, color); }

static inline void kl_draw_line_ex(vec2 startPos, vec2 endPos, float thick, Color color) { DrawLineEx((Vector2){startPos.x, startPos.y}, (Vector2){endPos.x, endPos.y}, thick, color); }

static inline void kl_draw_line_bezier(vec2 startPos, vec2 endPos, float thick, Color color) { DrawLineBezier((Vector2){startPos.x, startPos.y}, (Vector2){endPos.x, endPos.y}, thick, color); }

static inline void kl_draw_circle_sector(vec2 center, float radius, float startAngle, float endAngle, int segments, Color color) { DrawCircleSector((Vector2){center.x, center.y}, radius, startAngle, endAngle, segments, color); }

static inline void kl_draw_circle_sector_lines(vec2 center, float radius, float startAngle, float endAngle, int segments, Color color) { DrawCircleSectorLines((Vector2){center.x, center.y}, radius, startAngle, endAngle, segments, color); }

static inline void kl_draw_circle_v(vec2 center, float radius, Color color) { DrawCircleV((Vector2){center.x, center.y}, radius, color); }

static inline void kl_draw_circle_lines_v(vec2 center, float radius, Color color) { DrawCircleLinesV((Vector2){center.x, center.y}, radius, color); }

static inline void kl_draw_ring(vec2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color) { DrawRing((Vector2){center.x, center.y}, innerRadius, outerRadius, startAngle, endAngle, segments, color); }

static inline void kl_draw_ring_lines(vec2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color) { DrawRingLines((Vector2){center.x, center.y}, innerRadius, outerRadius, startAngle, endAngle, segments, color); }

static inline void kl_draw_rectangle_v(vec2 position, vec2 size, Color color) { DrawRectangleV((Vector2){position.x, position.y}, (Vector2){size.x, size.y}, color); }

static inline void kl_draw_rectangle_pro(Rectangle rec, vec2 origin, float rotation, Color color) { DrawRectanglePro(rec, (Vector2){origin.x, origin.y}, rotation, color); }

static inline void kl_draw_triangle(vec2 v1, vec2 v2, vec2 v3, Color color) { DrawTriangle((Vector2){v1.x, v1.y}, (Vector2){v2.x, v2.y}, (Vector2){v3.x, v3.y}, color); }

static inline void kl_draw_triangle_lines(vec2 v1, vec2 v2, vec2 v3, Color color) { DrawTriangleLines((Vector2){v1.x, v1.y}, (Vector2){v2.x, v2.y}, (Vector2){v3.x, v3.y}, color); }

static inline void kl_draw_poly(vec2 center, int sides, float radius, float rotation, Color color) { DrawPoly((Vector2){center.x, center.y}, sides, radius, rotation, color); }

static inline void kl_draw_poly_lines(vec2 center, int sides, float radius, float rotation, Color color) { DrawPolyLines((Vector2){center.x, center.y}, sides, radius, rotation, color); }

static inline void kl_draw_poly_lines_ex(vec2 center, int sides, float radius, float rotation, float lineThick, Color color) { DrawPolyLinesEx((Vector2){center.x, center.y}, sides, radius, rotation, lineThick, color); }

static inline bool kl_check_collision_circles(vec2 center1, float radius1, vec2 center2, float radius2) { return CheckCollisionCircles((Vector2){center1.x, center1.y}, radius1, (Vector2){center2.x, center2.y}, radius2); }

static inline bool kl_check_collision_circle_rec(vec2 center, float radius, Rectangle rec) { return CheckCollisionCircleRec((Vector2){center.x, center.y}, radius, rec); }

static inline bool kl_check_collision_circle_line(vec2 center, float radius, vec2 p1, vec2 p2) { return CheckCollisionCircleLine((Vector2){center.x, center.y}, radius, (Vector2){p1.x, p1.y}, (Vector2){p2.x, p2.y}); }

static inline bool kl_check_collision_point_rec(vec2 point, Rectangle rec) { return CheckCollisionPointRec((Vector2){point.x, point.y}, rec); }

static inline bool kl_check_collision_point_circle(vec2 point, vec2 center, float radius) { return CheckCollisionPointCircle((Vector2){point.x, point.y}, (Vector2){center.x, center.y}, radius); }

static inline bool kl_check_collision_point_triangle(vec2 point, vec2 p1, vec2 p2, vec2 p3) { return CheckCollisionPointTriangle((Vector2){point.x, point.y}, (Vector2){p1.x, p1.y}, (Vector2){p2.x, p2.y}, (Vector2){p3.x, p3.y}); }

static inline bool kl_check_collision_point_line(vec2 point, vec2 p1, vec2 p2, int threshold) { return CheckCollisionPointLine((Vector2){point.x, point.y}, (Vector2){p1.x, p1.y}, (Vector2){p2.x, p2.y}, threshold); }

static inline void kl_draw_texture_v(Texture2D texture, vec2 position, Color tint) { DrawTextureV(texture, (Vector2){position.x, position.y}, tint); }

static inline void kl_draw_texture_ex(Texture2D texture, vec2 position, float rotation, float scale, Color tint) { DrawTextureEx(texture, (Vector2){position.x, position.y}, rotation, scale, tint); }

static inline void kl_draw_texture_rec(Texture2D texture, Rectangle source, vec2 position, Color tint) { DrawTextureRec(texture, source, (Vector2){position.x, position.y}, tint); }

static inline void kl_draw_texture_pro(Texture2D texture, Rectangle source, Rectangle dest, vec2 origin, float rotation, Color tint) { DrawTexturePro(texture, source, dest, (Vector2){origin.x, origin.y}, rotation, tint); }

static inline void kl_draw_texture_n_patch(Texture2D texture, NPatchInfo nPatchInfo, Rectangle dest, vec2 origin, float rotation, Color tint) { DrawTextureNPatch(texture, nPatchInfo, dest, (Vector2){origin.x, origin.y}, rotation, tint); }

static inline vec4 kl_color_normalize(Color color) { Vector4 _r = ColorNormalize(color); return (vec4){ _r.x, _r.y, _r.z, _r.w }; }

static inline Color kl_color_from_normalized(vec4 normalized) { return ColorFromNormalized((Vector4){normalized.x, normalized.y, normalized.z, normalized.w}); }

static inline vec3 kl_color_to_hsv(Color color) { Vector3 _r = ColorToHSV(color); return (vec3){ _r.x, _r.y, _r.z }; }

static inline void kl_draw_text_ex(Font font, const char * text, vec2 position, float fontSize, float spacing, Color tint) { DrawTextEx(font, text, (Vector2){position.x, position.y}, fontSize, spacing, tint); }

static inline void kl_draw_text_pro(Font font, const char * text, vec2 position, vec2 origin, float rotation, float fontSize, float spacing, Color tint) { DrawTextPro(font, text, (Vector2){position.x, position.y}, (Vector2){origin.x, origin.y}, rotation, fontSize, spacing, tint); }

static inline void kl_draw_text_codepoint(Font font, int codepoint, vec2 position, float fontSize, Color tint) { DrawTextCodepoint(font, codepoint, (Vector2){position.x, position.y}, fontSize, tint); }

static inline vec2 kl_measure_text_ex(Font font, const char * text, float fontSize, float spacing) { Vector2 _r = MeasureTextEx(font, text, fontSize, spacing); return (vec2){ _r.x, _r.y }; }

static inline void kl_draw_line_3d(vec3 startPos, vec3 endPos, Color color) { DrawLine3D((Vector3){startPos.x, startPos.y, startPos.z}, (Vector3){endPos.x, endPos.y, endPos.z}, color); }

static inline void kl_draw_point_3d(vec3 position, Color color) { DrawPoint3D((Vector3){position.x, position.y, position.z}, color); }

static inline void kl_draw_circle_3d(vec3 center, float radius, vec3 rotationAxis, float rotationAngle, Color color) { DrawCircle3D((Vector3){center.x, center.y, center.z}, radius, (Vector3){rotationAxis.x, rotationAxis.y, rotationAxis.z}, rotationAngle, color); }

static inline void kl_draw_triangle_3d(vec3 v1, vec3 v2, vec3 v3, Color color) { DrawTriangle3D((Vector3){v1.x, v1.y, v1.z}, (Vector3){v2.x, v2.y, v2.z}, (Vector3){v3.x, v3.y, v3.z}, color); }

static inline void kl_draw_cube(vec3 position, float width, float height, float length, Color color) { DrawCube((Vector3){position.x, position.y, position.z}, width, height, length, color); }

static inline void kl_draw_cube_v(vec3 position, vec3 size, Color color) { DrawCubeV((Vector3){position.x, position.y, position.z}, (Vector3){size.x, size.y, size.z}, color); }

static inline void kl_draw_cube_wires(vec3 position, float width, float height, float length, Color color) { DrawCubeWires((Vector3){position.x, position.y, position.z}, width, height, length, color); }

static inline void kl_draw_cube_wires_v(vec3 position, vec3 size, Color color) { DrawCubeWiresV((Vector3){position.x, position.y, position.z}, (Vector3){size.x, size.y, size.z}, color); }

static inline void kl_draw_sphere(vec3 centerPos, float radius, Color color) { DrawSphere((Vector3){centerPos.x, centerPos.y, centerPos.z}, radius, color); }

static inline void kl_draw_sphere_ex(vec3 centerPos, float radius, int rings, int slices, Color color) { DrawSphereEx((Vector3){centerPos.x, centerPos.y, centerPos.z}, radius, rings, slices, color); }

static inline void kl_draw_sphere_wires(vec3 centerPos, float radius, int rings, int slices, Color color) { DrawSphereWires((Vector3){centerPos.x, centerPos.y, centerPos.z}, radius, rings, slices, color); }

static inline void kl_draw_cylinder(vec3 position, float radiusTop, float radiusBottom, float height, int slices, Color color) { DrawCylinder((Vector3){position.x, position.y, position.z}, radiusTop, radiusBottom, height, slices, color); }

static inline void kl_draw_cylinder_ex(vec3 startPos, vec3 endPos, float startRadius, float endRadius, int sides, Color color) { DrawCylinderEx((Vector3){startPos.x, startPos.y, startPos.z}, (Vector3){endPos.x, endPos.y, endPos.z}, startRadius, endRadius, sides, color); }

static inline void kl_draw_cylinder_wires(vec3 position, float radiusTop, float radiusBottom, float height, int slices, Color color) { DrawCylinderWires((Vector3){position.x, position.y, position.z}, radiusTop, radiusBottom, height, slices, color); }

static inline void kl_draw_cylinder_wires_ex(vec3 startPos, vec3 endPos, float startRadius, float endRadius, int sides, Color color) { DrawCylinderWiresEx((Vector3){startPos.x, startPos.y, startPos.z}, (Vector3){endPos.x, endPos.y, endPos.z}, startRadius, endRadius, sides, color); }

static inline void kl_draw_capsule(vec3 startPos, vec3 endPos, float radius, int slices, int rings, Color color) { DrawCapsule((Vector3){startPos.x, startPos.y, startPos.z}, (Vector3){endPos.x, endPos.y, endPos.z}, radius, slices, rings, color); }

static inline void kl_draw_capsule_wires(vec3 startPos, vec3 endPos, float radius, int slices, int rings, Color color) { DrawCapsuleWires((Vector3){startPos.x, startPos.y, startPos.z}, (Vector3){endPos.x, endPos.y, endPos.z}, radius, slices, rings, color); }

static inline void kl_draw_plane(vec3 centerPos, vec2 size, Color color) { DrawPlane((Vector3){centerPos.x, centerPos.y, centerPos.z}, (Vector2){size.x, size.y}, color); }

static inline void kl_draw_model(Model model, vec3 position, float scale, Color tint) { DrawModel(model, (Vector3){position.x, position.y, position.z}, scale, tint); }

static inline void kl_draw_model_ex(Model model, vec3 position, vec3 rotationAxis, float rotationAngle, vec3 scale, Color tint) { DrawModelEx(model, (Vector3){position.x, position.y, position.z}, (Vector3){rotationAxis.x, rotationAxis.y, rotationAxis.z}, rotationAngle, (Vector3){scale.x, scale.y, scale.z}, tint); }

static inline void kl_draw_model_wires(Model model, vec3 position, float scale, Color tint) { DrawModelWires(model, (Vector3){position.x, position.y, position.z}, scale, tint); }

static inline void kl_draw_model_wires_ex(Model model, vec3 position, vec3 rotationAxis, float rotationAngle, vec3 scale, Color tint) { DrawModelWiresEx(model, (Vector3){position.x, position.y, position.z}, (Vector3){rotationAxis.x, rotationAxis.y, rotationAxis.z}, rotationAngle, (Vector3){scale.x, scale.y, scale.z}, tint); }

static inline void kl_draw_model_points(Model model, vec3 position, float scale, Color tint) { DrawModelPoints(model, (Vector3){position.x, position.y, position.z}, scale, tint); }

static inline void kl_draw_model_points_ex(Model model, vec3 position, vec3 rotationAxis, float rotationAngle, vec3 scale, Color tint) { DrawModelPointsEx(model, (Vector3){position.x, position.y, position.z}, (Vector3){rotationAxis.x, rotationAxis.y, rotationAxis.z}, rotationAngle, (Vector3){scale.x, scale.y, scale.z}, tint); }

static inline void kl_draw_billboard(Camera camera, Texture2D texture, vec3 position, float scale, Color tint) { DrawBillboard(camera, texture, (Vector3){position.x, position.y, position.z}, scale, tint); }

static inline void kl_draw_billboard_rec(Camera camera, Texture2D texture, Rectangle source, vec3 position, vec2 size, Color tint) { DrawBillboardRec(camera, texture, source, (Vector3){position.x, position.y, position.z}, (Vector2){size.x, size.y}, tint); }

static inline void kl_draw_billboard_pro(Camera camera, Texture2D texture, Rectangle source, vec3 position, vec3 up, vec2 size, vec2 origin, float rotation, Color tint) { DrawBillboardPro(camera, texture, source, (Vector3){position.x, position.y, position.z}, (Vector3){up.x, up.y, up.z}, (Vector2){size.x, size.y}, (Vector2){origin.x, origin.y}, rotation, tint); }

static inline Mesh kl_gen_mesh_heightmap(Image heightmap, vec3 size) { return GenMeshHeightmap(heightmap, (Vector3){size.x, size.y, size.z}); }

static inline Mesh kl_gen_mesh_cubicmap(Image cubicmap, vec3 cubeSize) { return GenMeshCubicmap(cubicmap, (Vector3){cubeSize.x, cubeSize.y, cubeSize.z}); }

static inline bool kl_check_collision_spheres(vec3 center1, float radius1, vec3 center2, float radius2) { return CheckCollisionSpheres((Vector3){center1.x, center1.y, center1.z}, radius1, (Vector3){center2.x, center2.y, center2.z}, radius2); }

static inline bool kl_check_collision_box_sphere(BoundingBox box, vec3 center, float radius) { return CheckCollisionBoxSphere(box, (Vector3){center.x, center.y, center.z}, radius); }

static inline RayCollision kl_get_ray_collision_sphere(Ray ray, vec3 center, float radius) { return GetRayCollisionSphere(ray, (Vector3){center.x, center.y, center.z}, radius); }

static inline RayCollision kl_get_ray_collision_triangle(Ray ray, vec3 p1, vec3 p2, vec3 p3) { return GetRayCollisionTriangle(ray, (Vector3){p1.x, p1.y, p1.z}, (Vector3){p2.x, p2.y, p2.z}, (Vector3){p3.x, p3.y, p3.z}); }

static inline RayCollision kl_get_ray_collision_quad(Ray ray, vec3 p1, vec3 p2, vec3 p3, vec3 p4) { return GetRayCollisionQuad(ray, (Vector3){p1.x, p1.y, p1.z}, (Vector3){p2.x, p2.y, p2.z}, (Vector3){p3.x, p3.y, p3.z}, (Vector3){p4.x, p4.y, p4.z}); }

#endif // KL_RAYLIB_H
