// Package raylib registers the raylib vendor library with the Klang compiler.
//
// Import this package for side effects in any binary that should support raylib:
//
//	import _ "github.com/klang-lang/klang/libs/raylib"
package raylib

import (
	"github.com/klang-lang/klang/internal/analysis"
	"github.com/klang-lang/klang/internal/codegen"
)

func init() {
	analysis.RegisterVendor(&analysis.VendorLib{
		Modules: map[string][]analysis.StdlibFunc{
			"rl": {
				// Window
				{"init_window", "init_window(width:int, height:int, title:string)"},
				{"close_window", "close_window()"},
				{"window_should_close", "window_should_close():bool"},
				{"set_target_fps", "set_target_fps(fps:int)"},
				{"get_screen_width", "get_screen_width():int"},
				{"get_screen_height", "get_screen_height():int"},
				{"get_screen_size", "get_screen_size():vec2"},
				{"toggle_fullscreen", "toggle_fullscreen()"},
				{"is_window_resized", "is_window_resized():bool"},
				{"set_window_title", "set_window_title(title:string)"},
				{"set_window_size", "set_window_size(width:int, height:int)"},
				{"get_frame_time", "get_frame_time():float"},
				{"get_time", "get_time():float"},
				{"get_fps", "get_fps():int"},
				// Drawing
				{"begin_drawing", "begin_drawing()"},
				{"end_drawing", "end_drawing()"},
				{"clear_background", "clear_background(color:Color)"},
				{"begin_mode_2d", "begin_mode_2d(camera:Camera2D)"},
				{"end_mode_2d", "end_mode_2d()"},
				{"begin_mode_3d", "begin_mode_3d(camera:Camera3D)"},
				{"end_mode_3d", "end_mode_3d()"},
				// Shapes
				{"draw_line", "draw_line(x1:int, y1:int, x2:int, y2:int, color:Color)"},
				{"draw_line_v", "draw_line_v(start:vec2, end:vec2, color:Color)"},
				{"draw_circle", "draw_circle(x:int, y:int, radius:float, color:Color)"},
				{"draw_circle_v", "draw_circle_v(center:vec2, radius:float, color:Color)"},
				{"draw_rectangle", "draw_rectangle(x:int, y:int, w:int, h:int, color:Color)"},
				{"draw_rectangle_v", "draw_rectangle_v(pos:vec2, size:vec2, color:Color)"},
				{"draw_rectangle_rec", "draw_rectangle_rec(rec:Rectangle, color:Color)"},
				{"draw_rectangle_lines", "draw_rectangle_lines(x:int, y:int, w:int, h:int, color:Color)"},
				{"draw_triangle", "draw_triangle(v1:vec2, v2:vec2, v3:vec2, color:Color)"},
				// Text
				{"draw_text", "draw_text(text:string, x:int, y:int, size:int, color:Color)"},
				{"draw_text_ex", "draw_text_ex(font:Font, text:string, pos:vec2, size:float, spacing:float, color:Color)"},
				{"measure_text", "measure_text(text:string, size:int):int"},
				{"load_font", "load_font(path:string):Font"},
				{"unload_font", "unload_font(font:Font)"},
				// Textures
				{"load_texture", "load_texture(path:string):Texture2D"},
				{"unload_texture", "unload_texture(texture:Texture2D)"},
				{"draw_texture", "draw_texture(texture:Texture2D, x:int, y:int, tint:Color)"},
				{"draw_texture_v", "draw_texture_v(texture:Texture2D, pos:vec2, tint:Color)"},
				{"draw_texture_ex", "draw_texture_ex(texture:Texture2D, pos:vec2, rotation:float, scale:float, tint:Color)"},
				{"draw_texture_rec", "draw_texture_rec(texture:Texture2D, source:Rectangle, pos:vec2, tint:Color)"},
				{"draw_texture_pro", "draw_texture_pro(texture:Texture2D, source:Rectangle, dest:Rectangle, origin:vec2, rotation:float, tint:Color)"},
				// Input — keyboard
				{"is_key_pressed", "is_key_pressed(key:int):bool"},
				{"is_key_down", "is_key_down(key:int):bool"},
				{"is_key_released", "is_key_released(key:int):bool"},
				{"is_key_up", "is_key_up(key:int):bool"},
				// Input — mouse
				{"is_mouse_button_pressed", "is_mouse_button_pressed(button:int):bool"},
				{"is_mouse_button_down", "is_mouse_button_down(button:int):bool"},
				{"is_mouse_button_released", "is_mouse_button_released(button:int):bool"},
				{"get_mouse_position", "get_mouse_position():vec2"},
				{"get_mouse_x", "get_mouse_x():int"},
				{"get_mouse_y", "get_mouse_y():int"},
				{"get_mouse_wheel_move", "get_mouse_wheel_move():float"},
				// Input — gamepad
				{"is_gamepad_available", "is_gamepad_available(gamepad:int):bool"},
				{"is_gamepad_button_pressed", "is_gamepad_button_pressed(gamepad:int, button:int):bool"},
				{"is_gamepad_button_down", "is_gamepad_button_down(gamepad:int, button:int):bool"},
				{"get_gamepad_axis_movement", "get_gamepad_axis_movement(gamepad:int, axis:int):float"},
				// Audio
				{"init_audio_device", "init_audio_device()"},
				{"close_audio_device", "close_audio_device()"},
				{"load_sound", "load_sound(path:string):Sound"},
				{"play_sound", "play_sound(sound:Sound)"},
				{"load_music_stream", "load_music_stream(path:string):Sound"},
				{"play_music_stream", "play_music_stream(music:Sound)"},
				{"update_music_stream", "update_music_stream(music:Sound)"},
				{"stop_music_stream", "stop_music_stream(music:Sound)"},
				// Helpers
				{"color", "color(r:int, g:int, b:int, a:int):Color"},
				{"color_rgb", "color_rgb(r:int, g:int, b:int):Color"},
				{"rect", "rect(x:float, y:float, w:float, h:float):Rectangle"},
				{"camera2d", "camera2d(offset:vec2, target:vec2, rotation:float, zoom:float):Camera2D"},
				{"camera3d", "camera3d(position:vec3, target:vec3, up:vec3, fovy:float):Camera3D"},
			},
		},
		Namespaces: map[string][]analysis.StdlibFunc{
			"Colors": {
				{"LightGray", "Color"}, {"Gray", "Color"}, {"DarkGray", "Color"},
				{"Yellow", "Color"}, {"Gold", "Color"}, {"Orange", "Color"},
				{"Pink", "Color"}, {"Red", "Color"}, {"Maroon", "Color"},
				{"Green", "Color"}, {"Lime", "Color"}, {"DarkGreen", "Color"},
				{"SkyBlue", "Color"}, {"Blue", "Color"}, {"DarkBlue", "Color"},
				{"Purple", "Color"}, {"Violet", "Color"}, {"DarkPurple", "Color"},
				{"Beige", "Color"}, {"Brown", "Color"}, {"DarkBrown", "Color"},
				{"White", "Color"}, {"Black", "Color"}, {"Blank", "Color"},
				{"Magenta", "Color"}, {"RayWhite", "Color"},
			},
			"Key": {
				{"Space", "int"}, {"Enter", "int"}, {"Escape", "int"}, {"Backspace", "int"}, {"Tab", "int"},
				{"Up", "int"}, {"Down", "int"}, {"Left", "int"}, {"Right", "int"},
				{"A", "int"}, {"B", "int"}, {"C", "int"}, {"D", "int"}, {"E", "int"},
				{"F", "int"}, {"G", "int"}, {"H", "int"}, {"I", "int"}, {"J", "int"},
				{"K", "int"}, {"L", "int"}, {"M", "int"}, {"N", "int"}, {"O", "int"},
				{"P", "int"}, {"Q", "int"}, {"R", "int"}, {"S", "int"}, {"T", "int"},
				{"U", "int"}, {"V", "int"}, {"W", "int"}, {"X", "int"}, {"Y", "int"}, {"Z", "int"},
				{"F1", "int"}, {"F2", "int"}, {"F3", "int"}, {"F4", "int"},
				{"F5", "int"}, {"F6", "int"}, {"F7", "int"}, {"F8", "int"},
				{"F9", "int"}, {"F10", "int"}, {"F11", "int"}, {"F12", "int"},
				{"LeftShift", "int"}, {"RightShift", "int"},
				{"LeftControl", "int"}, {"RightControl", "int"},
				{"LeftAlt", "int"}, {"RightAlt", "int"},
			},
			"Mouse": {
				{"Left", "int"}, {"Right", "int"}, {"Middle", "int"},
			},
			"Gamepad": {
				{"LeftStickX", "int"}, {"LeftStickY", "int"},
				{"RightStickX", "int"}, {"RightStickY", "int"},
				{"LeftTrigger", "int"}, {"RightTrigger", "int"},
			},
		},
		Types: []string{
			"Color", "Rectangle", "Texture2D", "Font", "Sound",
			"Camera2D", "Camera3D",
		},
		TypeMembers: map[string][]analysis.CompletionItem{
			"Color": {
				{Label: "r", Detail: "int", Kind: analysis.CompletionKindField},
				{Label: "g", Detail: "int", Kind: analysis.CompletionKindField},
				{Label: "b", Detail: "int", Kind: analysis.CompletionKindField},
				{Label: "a", Detail: "int", Kind: analysis.CompletionKindField},
			},
			"Rectangle": {
				{Label: "x", Detail: "float", Kind: analysis.CompletionKindField},
				{Label: "y", Detail: "float", Kind: analysis.CompletionKindField},
				{Label: "width", Detail: "float", Kind: analysis.CompletionKindField},
				{Label: "height", Detail: "float", Kind: analysis.CompletionKindField},
			},
		},
		TypeFieldTypes: map[string]map[string]string{
			"Color":     {"r": "int", "g": "int", "b": "int", "a": "int"},
			"Rectangle": {"x": "float", "y": "float", "width": "float", "height": "float"},
		},
		BuiltinConstructors: map[string]string{
			"Color":     "Color(r:int, g:int, b:int, a:int)",
			"Rectangle": "Rectangle(x:float, y:float, width:float, height:float)",
		},
		BuiltinConstructorParams: map[string][]string{
			"Color":     {"int", "int", "int", "int"},
			"Rectangle": {"float", "float", "float", "float"},
		},
		CTypeMap: map[string]string{
			"Color":     "Color",
			"Texture2D": "Texture2D",
			"Font":      "Font",
			"Sound":     "Sound",
			"Camera2D":  "Camera2D",
			"Camera3D":  "Camera3D",
		},
		BuiltinIdents: []string{
			"Color", "Rectangle", "Texture2D", "Font", "Sound", "Camera2D", "Camera3D",
			"rl",
			"Colors", "Key", "Mouse", "Gamepad",
		},
	})

	codegen.RegisterVendorCodegen(&codegen.VendorCodegen{
		ModuleFuncs: map[string]map[string]string{
			"rl": {
				// Window management
				"init_window":          "InitWindow",
				"close_window":         "CloseWindow",
				"window_should_close":  "WindowShouldClose",
				"set_target_fps":       "SetTargetFPS",
				"get_screen_width":     "GetScreenWidth",
				"get_screen_height":    "GetScreenHeight",
				"get_screen_size":      "kl_get_screen_size",
				"toggle_fullscreen":    "ToggleFullscreen",
				"is_window_resized":    "IsWindowResized",
				"set_window_title":     "SetWindowTitle",
				"set_window_size":      "SetWindowSize",
				"get_frame_time":       "GetFrameTime",
				"get_time":             "GetTime",
				"get_fps":              "GetFPS",
				// Drawing
				"begin_drawing":        "BeginDrawing",
				"end_drawing":          "EndDrawing",
				"clear_background":     "ClearBackground",
				"begin_mode_2d":        "BeginMode2D",
				"end_mode_2d":          "EndMode2D",
				"begin_mode_3d":        "BeginMode3D",
				"end_mode_3d":          "EndMode3D",
				// Shapes
				"draw_line":            "DrawLine",
				"draw_line_v":          "kl_draw_line_v",
				"draw_circle":          "DrawCircle",
				"draw_circle_v":        "kl_draw_circle_v",
				"draw_rectangle":       "DrawRectangle",
				"draw_rectangle_v":     "kl_draw_rectangle_v",
				"draw_rectangle_rec":   "DrawRectangleRec",
				"draw_rectangle_lines": "DrawRectangleLines",
				"draw_triangle":        "DrawTriangle",
				// Text
				"draw_text":            "DrawText",
				"draw_text_ex":         "DrawTextEx",
				"measure_text":         "MeasureText",
				"load_font":            "LoadFont",
				"unload_font":          "UnloadFont",
				// Textures
				"load_texture":         "LoadTexture",
				"unload_texture":       "UnloadTexture",
				"draw_texture":         "DrawTexture",
				"draw_texture_v":       "kl_draw_texture_v",
				"draw_texture_ex":      "DrawTextureEx",
				"draw_texture_rec":     "DrawTextureRec",
				"draw_texture_pro":     "kl_draw_texture_pro",
				// Input - keyboard
				"is_key_pressed":       "IsKeyPressed",
				"is_key_down":          "IsKeyDown",
				"is_key_released":      "IsKeyReleased",
				"is_key_up":            "IsKeyUp",
				// Input - mouse
				"is_mouse_button_pressed":  "IsMouseButtonPressed",
				"is_mouse_button_down":     "IsMouseButtonDown",
				"is_mouse_button_released": "IsMouseButtonReleased",
				"get_mouse_position":       "kl_get_mouse_position",
				"get_mouse_x":             "GetMouseX",
				"get_mouse_y":             "GetMouseY",
				"get_mouse_wheel_move":    "GetMouseWheelMove",
				// Input - gamepad
				"is_gamepad_available":      "IsGamepadAvailable",
				"is_gamepad_button_pressed": "IsGamepadButtonPressed",
				"is_gamepad_button_down":    "IsGamepadButtonDown",
				"get_gamepad_axis_movement": "GetGamepadAxisMovement",
				// Audio
				"init_audio_device":    "InitAudioDevice",
				"close_audio_device":   "CloseAudioDevice",
				"load_sound":           "LoadSound",
				"unload_sound":         "UnloadSound",
				"play_sound":           "PlaySound",
				"stop_sound":           "StopSound",
				"load_music_stream":    "LoadMusicStream",
				"unload_music_stream":  "UnloadMusicStream",
				"play_music_stream":    "PlayMusicStream",
				"stop_music_stream":    "StopMusicStream",
				"update_music_stream":  "UpdateMusicStream",
				"set_master_volume":    "SetMasterVolume",
				// Misc
				"draw_fps":            "DrawFPS",
				"set_exit_key":        "SetExitKey",
				// Helpers
				"color":     "kl_color",
				"color_rgb": "kl_color_rgb",
				"rect":      "kl_rect",
				"camera2d":  "kl_camera2d",
				"camera3d":  "kl_camera3d",
			},
		},
		ConstNamespaces: map[string]map[string]string{
			"Colors": {
				"LightGray":  "LIGHTGRAY",
				"Gray":       "GRAY",
				"DarkGray":   "DARKGRAY",
				"Yellow":     "YELLOW",
				"Gold":       "GOLD",
				"Orange":     "ORANGE",
				"Pink":       "PINK",
				"Red":        "RED",
				"Maroon":     "MAROON",
				"Green":      "GREEN",
				"Lime":       "LIME",
				"DarkGreen":  "DARKGREEN",
				"SkyBlue":    "SKYBLUE",
				"Blue":       "BLUE",
				"DarkBlue":   "DARKBLUE",
				"Purple":     "PURPLE",
				"Violet":     "VIOLET",
				"DarkPurple": "DARKPURPLE",
				"Beige":      "BEIGE",
				"Brown":      "BROWN",
				"DarkBrown":  "DARKBROWN",
				"White":      "WHITE",
				"Black":      "BLACK",
				"Blank":      "BLANK",
				"Magenta":    "MAGENTA",
				"RayWhite":   "RAYWHITE",
			},
			"Key": {
				"Space":        "KEY_SPACE",
				"Escape":       "KEY_ESCAPE",
				"Enter":        "KEY_ENTER",
				"Tab":          "KEY_TAB",
				"Backspace":    "KEY_BACKSPACE",
				"Delete":       "KEY_DELETE",
				"Right":        "KEY_RIGHT",
				"Left":         "KEY_LEFT",
				"Down":         "KEY_DOWN",
				"Up":           "KEY_UP",
				"LeftShift":    "KEY_LEFT_SHIFT",
				"LeftCtrl":     "KEY_LEFT_CONTROL",
				"LeftAlt":      "KEY_LEFT_ALT",
				"RightShift":   "KEY_RIGHT_SHIFT",
				"RightCtrl":    "KEY_RIGHT_CONTROL",
				"RightAlt":     "KEY_RIGHT_ALT",
				"A": "KEY_A", "B": "KEY_B", "C": "KEY_C", "D": "KEY_D",
				"E": "KEY_E", "F": "KEY_F", "G": "KEY_G", "H": "KEY_H",
				"I": "KEY_I", "J": "KEY_J", "K": "KEY_K", "L": "KEY_L",
				"M": "KEY_M", "N": "KEY_N", "O": "KEY_O", "P": "KEY_P",
				"Q": "KEY_Q", "R": "KEY_R", "S": "KEY_S", "T": "KEY_T",
				"U": "KEY_U", "V": "KEY_V", "W": "KEY_W", "X": "KEY_X",
				"Y": "KEY_Y", "Z": "KEY_Z",
				"F1": "KEY_F1", "F2": "KEY_F2", "F3": "KEY_F3", "F4": "KEY_F4",
				"F5": "KEY_F5", "F6": "KEY_F6", "F7": "KEY_F7", "F8": "KEY_F8",
				"F9": "KEY_F9", "F10": "KEY_F10", "F11": "KEY_F11", "F12": "KEY_F12",
				"Zero": "KEY_ZERO", "One": "KEY_ONE", "Two": "KEY_TWO",
				"Three": "KEY_THREE", "Four": "KEY_FOUR", "Five": "KEY_FIVE",
				"Six": "KEY_SIX", "Seven": "KEY_SEVEN", "Eight": "KEY_EIGHT", "Nine": "KEY_NINE",
			},
			"Mouse": {
				"Left":   "MOUSE_BUTTON_LEFT",
				"Right":  "MOUSE_BUTTON_RIGHT",
				"Middle": "MOUSE_BUTTON_MIDDLE",
			},
			"Gamepad": {
				"LeftStickX":   "GAMEPAD_AXIS_LEFT_X",
				"LeftStickY":   "GAMEPAD_AXIS_LEFT_Y",
				"RightStickX":  "GAMEPAD_AXIS_RIGHT_X",
				"RightStickY":  "GAMEPAD_AXIS_RIGHT_Y",
				"LeftTrigger":  "GAMEPAD_AXIS_LEFT_TRIGGER",
				"RightTrigger": "GAMEPAD_AXIS_RIGHT_TRIGGER",
			},
		},
		ValueTypes: []string{
			"Color", "Rectangle", "Camera2D", "Camera3D",
			"Texture2D", "Font", "Sound", "Music",
		},
		TypeMap: map[string]string{
			"Color":     "Color",
			"Rectangle": "Rectangle",
			"Texture2D": "Texture2D",
			"Texture":   "Texture2D",
			"Font":      "Font",
			"Sound":     "Sound",
			"Music":     "Music",
			"Camera2D":  "Camera2D",
			"Camera3D":  "Camera3D",
		},
		ConstructorTypes: []string{"Color", "Rectangle"},
		ReturnTypes: map[string]string{
			// bool returns
			"window_should_close":      "bool",
			"is_window_resized":        "bool",
			"is_key_pressed":           "bool",
			"is_key_down":              "bool",
			"is_key_released":          "bool",
			"is_key_up":                "bool",
			"is_mouse_button_pressed":  "bool",
			"is_mouse_button_down":     "bool",
			"is_mouse_button_released": "bool",
			"is_gamepad_available":     "bool",
			"is_gamepad_button_pressed": "bool",
			"is_gamepad_button_down":   "bool",
			// int returns
			"get_screen_width":  "int",
			"get_screen_height": "int",
			"get_fps":           "int",
			"measure_text":      "int",
			"get_mouse_x":       "int",
			"get_mouse_y":       "int",
			// float returns
			"get_frame_time":           "float",
			"get_time":                 "float",
			"get_mouse_wheel_move":     "float",
			"get_gamepad_axis_movement": "float",
			// vec2 returns
			"get_mouse_position": "vec2",
			"get_screen_size":    "vec2",
			// Texture2D returns
			"load_texture": "Texture2D",
			// Font returns
			"load_font": "Font",
			// Sound returns
			"load_sound": "Sound",
			// Music returns
			"load_music_stream": "Music",
			// Color returns
			"color":     "Color",
			"color_rgb": "Color",
			// Rectangle returns
			"rect": "Rectangle",
			// Camera returns
			"camera2d": "Camera2D",
			"camera3d": "Camera3D",
		},
		DetectIdents: []string{"rl", "Colors", "Key", "Mouse", "Gamepad"},
		DetectModule: "rl",
	})
}
